### ISSUE TITLE
okay we someone needs to update the versions.md list!

### ISSUE THREAD

**Issue by webbrowser11** [Scratch-Computng-Alliance/SolarOS-Archive#3]
the versions list is way behind someone update we are 22!

**Comment by 31parkjulianTehCoder** [comment]
what about the releases (the last one uploaded to the repository was build 11)

**Comment by Katelyn-software** [comment]
Yeah, someone has to update the builds list and the releases since they are behind the current release

**Comment by webbrowser11** [comment]
hey and can u guys help me i still need to activate 2FA on github and i am having some trouble...

**Comment by webbrowser11** [comment]
oh never mind WHEW! i figured it out!

**Comment by webbrowser11** [comment]
its so frikin! hard to enable

**Comment by webbrowser11** [comment]
okay we do need to add more releases and more to the versions.md list so we have figured that out i am closing this issue

**Comment by webbrowser11** [comment]
3... 2... 1...
