### ISSUE TITLE
this aint an issue but...

### ISSUE THREAD

**Issue by 31parkjulianTehCoder** [Scratch-Computng-Alliance/SolarOS-Archive#5]
i was thinking... what if we made an app live flashpoint that has like links to every version of every sca os? and if we did make that it would replace this

**Comment by webbrowser11** [comment]
https://github.com/cWorksLLC please add him

**Comment by webbrowser11** [comment]
yeah i guess we can

**Comment by 31parkjulianTehCoder** [comment]
> yeah i guess we can

i made a new website called skyhub its like this idea
https://sites.google.com/view/skyhubsca/home

**Comment by webbrowser11** [comment]
okay ill replace the repo if you give me acsess
